"""workout_api

Revision ID: 982b7f29ab86
Revises: c006e8463eb4
Create Date: 2024-06-27 15:45:20.639267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982b7f29ab86'
down_revision = 'c006e8463eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
